parameters:
  - name: terraformArtifactName
    type: string
    default: 'terraform'
    displayName: 'Name of the Terraform Plan artifact'
  - name: vmImage
    type: string
    default: 'ubuntu-latest'
    displayName: 'Pool vmImage' 
  - name: dependsOn
    type: string
    default: ''
    displayName: 'Name of the Stage which the Terraform Plan stage should wait on'

stages:
##### DEV #####
- template: deploy_aws_v2.yml
  parameters:
    environment: 'DEV'
    backendAWSBucketName: 'tandlterraform'

##### QA #####
- template: deploy_aws_v2.yml
  parameters:
    environment: 'QA'
    dependsOn: 'DEV_Apply'
    backendAWSBucketName: 'tandlterraform'

##### PROD #####
- template: deploy_aws_v2.yml
  parameters:
    environment: 'PROD'
    dependsOn: 'QA_Apply'
    backendAWSBucketName: 'tandlterraform'