parameters:
  - name: terraformArtifactName
    type: string
    default: 'terraform'
    displayName: 'Name of the Terraform Plan artifact'
  - name: vmImage
    type: string
    default: 'ubuntu-latest'
    displayName: 'Pool vmImage' 
  - name: dependsOn
    type: string
    default: ''
    displayName: 'Name of the Stage which the Terraform Plan stage should wait on'

stages:
##### DEV #####
- template: deploy_aws_v1.yml
  parameters:
    environemnt: 'DEV'


